### ISSUE TITLE
python使用3.8.3版本，存在报错

### ISSUE THREAD

**Issue by luojianxhlxt** [zhongfly/telegram-bot-asf#12]
因为官网没有3.6版本的下载，所以尝试的3.8版本

执行完
pip install -r requirements.txt
后

报错如下
`python telegram-asf.py
使用默认路径载入配置文件
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\contrib\socks.py:32: DependencyWarning: SOCKS support in urllib3 requires the installation of optional dependencies: specifically, PySocks.  For more information, see https://urllib3.readthedocs.io/en/latest/contrib.html#socks-proxies
  warnings.warn((
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\telegram\utils\request.py", line 151, in __init__
    from telegram.vendor.ptb_urllib3.urllib3.contrib.socks import SOCKSProxyManager
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\contrib\socks.py", line 27, in <module>
    import socks
ModuleNotFoundError: No module named 'socks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "telegram-asf.py", line 40, in <module>
    updater = Updater(token, request_kwargs={'proxy_url': proxy})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\telegram\ext\updater.py", line 159, in __init__
    self._request = Request(**request_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\telegram\utils\request.py", line 153, in __init__
    raise RuntimeError('PySocks is missing')
RuntimeError: PySocks is missing`

**Comment by zhongfly** [comment]
如果使用代理，请安装pysocks

pip install pysocks


ChienLo <notifications@github.com> 于 2020年6月10日周三 13:45写道：
