### ISSUE TITLE
3.6.8版本的Python 运行telegram-asf.py报错

### ISSUE THREAD

**Issue by ECHOWIKM** [zhongfly/telegram-bot-asf#20]
C:\Users\Administrator\Desktop\telegram-bot-asf-master>python3 telegram-asf.py

C:\Users\Administrator\Desktop\telegram-bot-asf-master>python telegram-asf.py
Traceback (most recent call last):
  File "telegram-asf.py", line 4, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler, Filters, CallbackQueryHandler, ConversationHandler
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\__init__.py", line 31, in <module>
    from .updater import Updater
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\updater.py", line 55, in <module>
    class Updater(Generic[CCT, UD, CD, BD]):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\updater.py", line 198, in Updater
    dispatcher: Dispatcher[CCT, UD, CD, BD] = None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\typing.py", line 682, in inner
    return func(*args, **kwds)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\typing.py", line 1143, in __getitem__
    orig_bases=self.__orig_bases__)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\typing.py", line 978, in __new__
    self = super().__new__(cls, name, bases, namespace, _root=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\typing.py", line 137, in __new__
    return super().__new__(cls, name, bases, namespace)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: __dict__ slot disallowed: we already got one

**Comment by zhongfly** [comment]
请确认依赖库版本是否在限定范围内 python-telegram-bot >= 12.8,<20.0
方法：
```
pip show python-telegram-bot
```

**Comment by ECHOWIKM** [comment]
python-telegram-bot在13.15
C:\Users\Administrator>pip list
Package               Version
--------------------- -----------
aiohttp               3.8.4
aiosignal             1.3.1
aiotg                 2.0.0
APScheduler           3.6.3
ASF-IPC               2.1.0
async-timeout         4.0.2
attrs                 22.2.0
backports.zoneinfo    0.2.1
cachetools            4.2.2
cchardet              2.1.7
certifi               2022.12.7
charset-normalizer    3.1.0
frozenlist            1.3.3
idna                  3.4
multidict             6.0.4
pip                   19.2.3
python-telegram-bot   13.15
pytz                  2022.7.1
pytz-deprecation-shim 0.1.0.post0
requests              2.28.2
setuptools            41.2.0
six                   1.16.0
toml                  0.10.2
tornado               6.1
tzdata                2022.7
tzlocal               4.3
urllib3               1.26.15
watchdog              2.3.1
yarl                  1.8.2

**Comment by ECHOWIKM** [comment]
C:\Users\Administrator\Desktop\telegram-bot-asf-master>pip show python-telegram-bot
Name: python-telegram-bot
Version: 13.15
Summary: We have made you a wrapper you can't refuse
Home-page: https://python-telegram-bot.org/
Author: Leandro Toledo
Author-email: devs@python-telegram-bot.org
License: LGPLv3
Location: c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages
Requires: tornado, cachetools, certifi, pytz, APScheduler
Required-by:

**Comment by ECHOWIKM** [comment]
fine,现在解决了
好像是代理没开的原因

**Comment by zhongfly** [comment]
我还以为是不支持v13版本……那样的话真没时间修改重写了
