### ISSUE TITLE
第五步安装依赖出错求解决方法

### ISSUE THREAD

**Issue by lacafjh** [zhongfly/telegram-bot-asf#5]
Debian系统 python更新到了3.7.1
求问进行到这一步
```
pip install -r requirements.txt
```

显示
```
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 67, in <module>
    vendored("distro")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/distro-1.0.1-py2.py3-none-any.whl/distro.py", line 1051, in <module>
  File "/usr/share/python-wheels/distro-1.0.1-py2.py3-none-any.whl/distro.py", line 595, in __init__
  File "/usr/share/python-wheels/distro-1.0.1-py2.py3-none-any.whl/distro.py", line 934, in _get_lsb_release_info
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 126
```

看最后一行的意思应该是安装出错了？这是出了什么情况？求教

**Comment by zhongfly** [comment]
pip改成pip3吧，感觉是用了系统自带的python2.7而不是你新安装的python3

静海闲人 <notifications@github.com> 于 2018年11月25日周日 21:39写道：

**Comment by lacafjh** [comment]
> pip改成pip3吧，感觉是用了系统自带的python2.7而不是你新安装的python3 静海闲人 <notifications@github.com> 于 2018年11月25日周日 21:39写道：

确实是你说的问题，但是换用pip3又告诉我找不到指令。去网上了下，搜按教程更新升级了一下pip，之后直接用pip重新安装就成功了。
```
 pip install -r requirements.txt
Collecting python-telegram-bot>=10.1.0 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/84/6c/47932a4041ee76650ad1f45a80e1422077e1e99c08a4d7a61cfbe5393d41/python_telegram_bot-11.1.0-py2.py3-none-any.whl (326kB)
    100% |████████████████████████████████| 327kB 15.3MB/s 
Collecting requests (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 13.4MB/s 
Collecting certifi (from python-telegram-bot>=10.1.0->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl (146kB)
    100% |████████████████████████████████| 153kB 19.3MB/s 
Requirement already satisfied: cryptography in /usr/lib/python2.7/dist-packages (from python-telegram-bot>=10.1.0->-r requirements.txt (line 4)) (1.7.1)
Collecting future>=0.16.0 (from python-telegram-bot>=10.1.0->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 10.7MB/s 
Collecting idna<2.8,>=2.5 (from requests->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 13.2MB/s 
Collecting urllib3<1.25,>=1.21.1 (from requests->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 21.2MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 20.7MB/s 
Building wheels for collected packages: future
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /root/.cache/pip/wheels/0c/61/d2/d6b7317325828fbb39ee6ad559dbe4664d0896da4721bf379e
Successfully built future
Installing collected packages: certifi, future, python-telegram-bot, idna, urllib3, chardet, requests
  Found existing installation: idna 2.2
    Uninstalling idna-2.2:
      Successfully uninstalled idna-2.2
Successfully installed certifi-2018.10.15 chardet-3.0.4 future-0.17.1 idna-2.7 python-telegram-bot-11.1.0 requests-2.20.1 urllib3-1.24.1
```

不过接着运行的时候又出现了新的问题，就是我在你帖子下面发的那个
输入
```
python3 telegram-asf.py
```
显示
```
Traceback (most recent call last):
  File "telegram-asf.py", line 3, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler, Filters, Job, CallbackQueryHandler, ConversationHandler
ModuleNotFoundError: No module named 'telegram'
root@JH_Amateur001:~/telegram-bot-asf# python telegram-asf.py
Traceback (most recent call last):
  File "telegram-asf.py", line 9, in <module>
    from urllib.parse import urljoin
ImportError: No module named parse
```

**Comment by zhongfly** [comment]
这种python3新版本带来的问题我现在没时间处理…

静海闲人 <notifications@github.com> 于 2018年11月25日周日 22:19写道：

**Comment by lacafjh** [comment]
今天闲着把主机回退了装了3.6，但是到最后一步`python3 telegram-asf.py`又出现了不同的问题
```
2018-12-01 09:22:42,270 - root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2018-12-01 09:22:42,271 - root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2018-12-01 09:22:42,271 - root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
```
这个情况有什么可能的解决方法吗
*python v3.6.0，pip v18.1

> 这种python3新版本带来的问题我现在没时间处理…

**Comment by zhongfly** [comment]
这是正常提示，毫无问题…不用担心，已经在运行了。
所用的telegram bot的依赖库还没适配3.7，所以在python3.7上可能存在问题
目前用3.6就可以了

静海闲人 <notifications@github.com> 于 2018年12月1日周六 17:25写道：
